CREATE DATABASE IF NOT EXISTS db_auth;
CREATE DATABASE IF NOT EXISTS db_menu;
CREATE DATABASE IF NOT EXISTS db_reservation;
CREATE DATABASE IF NOT EXISTS db_cart;
CREATE DATABASE IF NOT EXISTS db_special;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
