name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build . \
            -f Dockerfile \
            -t jordanians/kerapu:latest \
            -t jordanians/kerapu:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push jordanians/kerapu:latest
          docker push jordanians/kerapu:${{ github.sha }}
